version: '3'
services:
  worker:
    build: .
    command: celery -A src.service.celery_worker worker --loglevel=info -E --logfile=./logs/logfile.log
    volumes:
      - ./logs:/logs
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

  beat:
    build: .
    command: celery -A src.service.celery_worker beat --loglevel=info
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

  flower:
    image: mher/flower
    command: flower --broker=${CELERY_BROKER_URL} --port=${FLOWER_PORT} --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}
    ports:
      - ${HOST_FLOWER_PORT}:${FLOWER_PORT}
    env_file:
      - .env