FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["flower", "--broker=${CELERY_BROKER_URL}", "--port=${FLOWER_PORT}", "--basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}"]